-- S2U-42 --
CREATE TABLE CARDGAME_STAT_ITEM (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  PLAYER_ID VARCHAR(255) NOT NULL,
  USER_ID VARCHAR(255) NOT NULL,
  HITS SMALLINT(6) DEFAULT 0 NULL,
  MISSES SMALLINT(6) DEFAULT 0 NULL
);

#CREATE INDEX SAM_SEB_INDEX ON SAM_SEBVALIDATION_T (PUBLISHEDASSESSMENTID, AGENTID);
-- END S2U-42 --
